[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1028

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "warning"